[package]
name = "scan"
version = "0.1.0"
edition = "2021"

[profile.optimized]
inherits = "release"
codegen-units = 1
lto = "fat"
panic = "abort"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = ["scan_core", "scan_fmt_xml"]

[workspace.dependencies]
log = "0.4.20"

[dependencies]
scan_fmt_xml = { version = "0.1.0", path = "scan_fmt_xml" }
clap = { version = "4.4.14", features = ["derive"] }
env_logger = "0.11.0"
log = { workspace = true }
indicatif = { version = "0.17.8", features = ["improved_unicode"] }
csv = "1.3.1"
flate2 = "1.0.34"
