[package]
name = "scan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = ["scan_core", "scan_fmt_xml"]

[dependencies]
scan_fmt_xml = { path = "scan_fmt_xml" }
anyhow = "1.0.79"
clap = { version = "4.4.14", features = ["derive"] }
log = "0.4.21"
env_logger = "0.11.3"
