name: Docs
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  
on:
  pull_request_target:
    types:
      - closed
      
env:
  CARGO_TERM_COLOR: always

jobs:
  docs-build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Install and Build 🔧 
        run: |
          cargo doc --no-deps --workspace
          echo "<meta http-equiv=\"refresh\" content=\"0; url=scan\">" > target/doc/index.html
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: 'target/doc'

  docs-deploy:
    if: github.event.pull_request.merged == true
    needs: docs-build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: docs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: docs
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          name: docs
