name: Rust

permissions:
  contents: read
  
on: [pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check
      run: cargo check --verbose
    - name: Check fmt
      run: cargo fmt --all -- --check
    - name: Run tests
      run: cargo test --verbose --workspace
