name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose --workspace
    - name: Build docs
      run: cargo doc --no-deps --workspace
    - name: Deploy docs
      run: rm -rf ./docs; echo "<meta http-equiv=\"refresh\" content=\"0; url=scan\">" > target/doc/index.html; cp -r target/doc ./docs
